### ISSUE TITLE
F0530 02:11:55.654647  4861 hdf5_data_layer.cpp:89] Failed to open source file: /home/trakis/Downloads/MPIIGaze/Data/train_list.txt

### ISSUE THREAD

**Issue by zhaolei-momo** [trakaros/MPIIGaze#1]
Is it possible to upload the train_list.txt, test_list.txt and the readme.md about how to run this code? 
thank you!

**Comment by caxelos** [comment]
Hi


***** Is it possible to upload the train_list.txt, test_list.txt********
Basically its not difficult to think what these txt files have
They contain a LIST OF PATHS to hdf files(or other type of database)

For example:

train_list.txt:
/home/user/training/1st.hdf
/home/user/training/2nd.hdf
/home/user/training/3rd.hdf

In my example I use all training data in  one hdf so:
/home/user/training/all.hdf

Similarly in testing phase

 ******* how to run this code *************
You must put them in the .prototxt model file, something like this
https://github.com/trakaros/MPIIGaze/blob/master/train_test.prototxt

I don't have yet a README file, however i am thinking making one
Quoting Zhao Lei <notifications@github.com>:

**Comment by zhaolei-momo** [comment]
Thank you! I will have a try.
